development:
  adapter: postgresql
  database: myersbits_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: myersbits_development
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: myersbits_development
  pool: 5
  timeout: 5000


